<div class="col-md-6">
  <!-- lo quiero con fondo amarillo a este-->
  <section class="clubes bg-light p-3">
      <h2>Advertencia</h2>
      <p>El club que desea eliminar aún posee jugadores cargados</p>
        <!-- boton azul -->
      <a class="btn btn-primary" href="listarClubes">Mmm... bueno, entonces mejor no</a>
        <!-- boton rojo -->
      <a class="btn btn-primary" href="eliminarClub/<?= $clubNew->id_club ?>">Eliminar "<?= $clubNew->nombre ?>" de todas formas</a>
  </section>
</div>