<h3 class="mb-3">+ Agregar Club</h3>
<form class="row g-3 d-flex justify-content-between align-items-end">
  <div class="col-md-2">
    <!-- que es este "for" en el label?-->
    <label for="nombre" class="form-label">Nombre</label>
    <input type="text" class="form-control" id="nombre">
  </div>
  <div class="col-md-2">
    <label for="fecha_creacion" class="form-label">Fecha de inauguración</label>
    <input type="date" class="form-control" id="fecha_creacion">
  </div>
  <div class="col-md-2">
    <label for="ubicacion" class="form-label">Ubicación Sede</label>
    <input type="text" class="form-control" id="ubicacion">
  </div>
  <div class="col-md-2">
    <label for="estadio" class="form-label">Estadio</label>
    <input type="text" class="form-control" id="estadio">
  </div>
  <div class="col-md-2">
    <label for="campeonatos_locales" class="form-label">Campeonatos locales alcanzados</label>
    <input type="number" class="form-control" id="campeonatos_locales">
  </div>
  <div class="col-md-2">
    <button type="submit" class="btn btn-primary">Agregar</button>
  </div>
</form>