<?php require_once 'templates/header.phtml' ?>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title"><?= $club->nombre ?></h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Fecha de inauguración: <?= $club->fecha_creacion ?></li>
            <li class="list-group-item">Ubicación Sede: <?= $club->ubicacion ?></li>
            <li class="list-group-item">Estadio: <?= $club->estadio ?></li>
            <li class="list-group-item">Campeonatos locales alcanzados: <?= $club->campeonatos_locales ?></li>
        </ul>
    </div>
</div>
<?php if ($llamadoDesde=='modificarClub') : ?>
  <div class='alert alert-success' role='alert'>
    <p> El club se modificó correctamente </p>
  </div> 
<?php endif ?>
<ul class="list-group">
  <?php foreach ($jugadores as $jugador) { ?>
    <li class="list-group-item">
        <div class="col-md-6">
          <h4><?= $jugador->nombre ?></h4>
          <p>Club: <?= $jugador->nombre_club ?></p>
        </div>
    </li>
  <?php } ?>
</ul>

<?php require_once 'templates/Footer.phtml' ?>