  <form action="agregarClub" method="POST" class="row g-3 d-flex justify-content-between align-items-end">
    <div class="col-md-2">
      <label for="nombre" class="form-label">Nombre</label>
      <input type="text" class="form-control" name="nombre" required>
    </div>
    <div class="col-md-2">
      <label for="fecha_creacion" class="form-label">Fecha de inauguración</label>
      <input type="date" class="form-control" name="fecha_creacion" required>
    </div>
    <div class="col-md-2">
      <label for="ubicacion" class="form-label">Ubicación Sede</label>
      <input type="text" class="form-control" name="ubicacion" required>
    </div>
    <div class="col-md-2">
      <label for="estadio" class="form-label">Estadio</label>
      <input type="text" class="form-control" name="estadio" required>
    </div>
    <div class="col-md-2">
      <label for="campeonatos_locales" class="form-label">Campeonatos locales alcanzados</label>
      <input type="number" class="form-control" name="campeonatos_locales" required>
    </div>
    <div class="col-md-2">
      <button type="submit" class="btn btn-primary">Agregar</button>
    </div>
  </form>