<form class="row g-3 d-flex justify-content-between align-items-end">
  <div class="col-md-2">
    <label for="nombre" class="form-label">Nombre</label>
    <input type="text" class="form-control" id="nombre">
  </div>
  <div class="col-md-2">
    <label for="nacionalidad" class="form-label">Nacionalidad</label>
    <input type="text" class="form-control" id="nacionalidad">
  </div>
  <div class="col-md-2">
    <label for="posicion" class="form-label">Posicion</label>
    <input type="text" class="form-control" id="posicion">
  </div>
  <div class="col-md-2">
    <label for="edad" class="form-label">Edad</label>
    <input type="number" class="form-control" id="edad">
  </div>
  <div class="col-md-2">
    <label for="pie_habil" class="form-label">Pie Habil</label>
    <select id="pie_habil" class="form-select">
      <option selected disabled>Seleccionar...</option>
        <option value="diestro">Diestro</option>
        <option value="zurdo">Zurdo</option>
    </select>
  </div>
  <div class="col-md-2">
    <label for="club" class="form-label">Club</label>
    <select id="club" class="form-select">
      <option selected disabled>Seleccionar...</option>
      <?php foreach ($clubes as $club) {?>
        <option value="<?= $club->id_club ?>"><?= $club->nombre ?></option>
      <?php } ?>
    </select>
  </div>
  <div class="col-md-2">
    <button type="submit" class="btn btn-primary">Agregar</button>
  </div>
</form>