<?php require_once 'templates/Header.phtml' ?>

<form class="row g-3 d-flex justify-content-between align-items-end" method="POST" action="modificarJugador/<?= $jugador->id_jugador ?>">
  <div class="col-md-2 text-center">
    <h3 class="form-label">Nombre</h3>
    <input type="text" class="form-control" name="nombre" value='<?= $jugador->nombre ?>'>
  </div>
  <div class="col-md-1 text-center">
    <h3 class="form-label">Edad</h3>
    <input type="number" class="form-control" name="edad" value='<?= $jugador->edad ?>'>
  </div>
  <div class="col-md-2 text-center">
    <h3 class="form-label">Nacionalidad</h3>
    <input type="text" class="form-control" name="nacionalidad" value='<?= $jugador->nacionalidad ?>'>
  </div>
  <div class="col-md-2 text-center">
    <h3 class="form-label">Posicion</h3>
    <input type="text" class="form-control" name="posicion" value='<?= $jugador->posicion ?>'>
  </div>
  <div class="col-md-2 text-center">
    <h3 class="form-label">Pie Habil</h3>
    <select name="pie_habil" class="form-select">
      <option selected disabled>Seleccionar...</option>
      <option value="derecho">Derecho</option>
      <option value="izquierdo">Izquierdo</option>
    </select>
  </div>
  <div class="col-md-2 text-center">
    <h3 class="form-label">Club</h3>
    <select name="id_club" class="form-select">
      <option selected disabled>Seleccionar...</option>
      <?php foreach ($clubes as $club) {?>
        <option value="<?= $club->id_club ?>"><?= $club->nombre ?></option>
      <?php } ?>
    </select>
  </div>
  <div class="col-md-2">
    <button type="submit" class="btn btn-primary">Modificar</button>
  </div>
</form>
<a href="listarJugadores" class="btn btn-primary mt-3">Volver a la Lista</a>   

<?php require_once 'templates/Footer.phtml' ?>
