<?php require_once 'templates/Header.phtml' ?>

<div class="text-center">
            <h1>Bienvenido a la página oficial de la AFA</h1>
            <p>En las distintas secciones del la barra de navegacion o dandole al boton de ver jugadores/clubes podrás explorar los Jugadores y Clubes de nuestra Asociación.</p>
        </div>
        <div class="secciones mt-5">
            <div class="row">
                <div class="col-md-6">
                    <section class="jugadores bg-light p-3">
                        <h2>Jugadores</h2>
                        <p>Descubre a nuestros talentosos jugadores y sus estadísticas.</p>
                        <a class="btn btn-primary" href="listarJugadores">Ver Jugadores</a>
                    </section>
                </div>
                <div class="col-md-6">
                    <section class="clubes bg-light p-3">
                        <h2>Clubes</h2>
                        <p>Explora nuestros clubes afiliados y su información relevante.</p>
                        <a class="btn btn-primary" href="listarClubes/''/''">Ver Clubes</a>
                    </section>
                </div>
            </div>
        </div>

<?php require_once 'templates/Footer.phtml' ?>
