<?php require_once 'templates/Header.phtml' ?>

<div class="container mt-4">
    <div class="card">
        <div class="card-header">
            <h5 class="card-title"><?= $jugador->nombre ?></h5>
        </div>
        <ul class="list-group list-group-flush">
            <li class="list-group-item">Edad: <?= $jugador->edad ?></li>
            <li class="list-group-item">Nacionalidad: <?= $jugador->nacionalidad ?></li>
            <li class="list-group-item">Posicion: <?= $jugador->posicion ?></li>
            <li class="list-group-item">Pie Habil: <?= $jugador->pie_habil ?></li>
            <li class="list-group-item">Club: <?= $jugador->nombre_club ?></li>
        </ul>
    </div>
    <a href="listarJugadores" class="btn btn-primary mt-3">Volver a la lista</a>
</div>

<?php require_once 'templates/Footer.phtml' ?>