<h1 class="display-5 text-center">Clubes de la Asociación de Fútbol Argentino</h1>
<ul class="list-group">
  <?php foreach ($clubes as $club) { ?>
    <li class="list-group-item">
      <div class="row">
        <div class="col-md-6">
          <h4><?= $club->nombre ?></h4>
        </div>
        <div class="col-md-6 text-md-end">
          <div class="d-flex justify-content-end align-items-center mt-2 mb-3">
          <a href="club/<?= $club->id_club ?>" class="btn btn-secondary ms-2">Ver Detalles</a>
          <?php if(isset($_SESSION['USER_ID'])) : ?>
            <a href="formModificarClub/<?= $club->id_club ?>" class="btn btn-primary ms-2">Modificar</a>
            <a href="solicitudEliminarClub/<?= $club->id_club ?>" type="button" class="btn btn-danger ms-2">Eliminar Club</a>
          <?php endif ?>
          </div>
        </div>
        
      </div>
    </li>
    <?php } ?>
  </ul>